name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        if: ${{ !startsWith(github.event.pull_request.title, github.event.pull_request.head.ref) }}
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          if [[ ! $TITLE =~ ^[A-Z]+-[0-9]+: ]]; then
            echo "❌ PR title must start with JIRA ticket (e.g., JIRA-123: description)"
            exit 1
          fi
          echo "✅ PR title format is valid"
